server:
  port: 8762 # 端口

spring:
  application:
    name: eureka-server-02 # 应用名称

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: eureka02
  client:
    service-url: #注册中心对外暴露的注册地址
      defaultZone: http://localhost:8761/eureka/